function BuildApplication(){if(device.isOS.iOS&&(device.iOSWebView)){scannerAppBrowser();}
if(device.isOS.Playbook||device.isOS.Blackberry||device.downgraded){$('#pattern').remove();}
showPageLoadingMsg();if(onecard.cardid==null||onecard.cardid==""){onecard.cardid=lookForCardIDRequest();}
if(onecard.company==null||onecard.company==""){onecard.parent=lookForCompanyRequest();}
if(onecard.cardid!=null){var cardid=onecard.cardid;if(onecard.company&&onecard.company!=''){cardid=onecard.company+"/"+cardid;}
if(store&&store.getFor(cardid)==null){onecard.firstime=true;}
loadCurrentCard();}else{window.location='http://onecardme.com/home/';}
markEnvironment();$('.menu .os').text(device.OS);$('.menu .osversion').text(device.OSVersion);$('.menu .browser').text(device.Browser);$('.menu .browserversion').text(device.BrowserVersion);$('.menu .renderer').text(device.RenderingEngine);$('.menu .rendererversion').text(device.RenderingEngineVersion);if($_GET['debug']=="true"){loadDebuging();}}
function BuildCardForApplication(){if(getParam('page')!=null){changePage(getParam('page'));}else{loadCurrentPage();}
loadAccentColor();loadTheme();loadCardImages();rewireIframe();loadTouchIcons();loadDefaultStartImage();updateBrowserAddressForPage(getCurrentPageID()+'.html',true);if(isMobile()&&!device.iOSStandalone&&onecard.firstime){displayFirstTimeVisit();}
if(isMobile()&&device.iOSStandalone&&device.OS=='iOS'){if(device.iOS.Version==7&&device.iOS.SubVerions==0){if(device.iOS.Revision>=0&&device.iOS.Revision<3){displayiOS7ErrorMessage(onecard.cardid);}}}}
function displayiOS7ErrorMessage(cardid){var html='Please update your device\'s software. Apple\'s release of iOS 7 included a bug that affected WebApps saved to the homescreen. This bug was fixed with the release of <b>iOS 7.0.3</b>. Please update your device to restore full functionality to your One Card™. ';displayError('iOS 7 Bug',html,'For instructions on updating your device visit http://support.apple.com/kb/HT4623 on your desktop or laptop device.');}
function loadUIElements(page){var id=$(page).attr('id');switch(id){case"index":case"bio":case"staff":case"social":case"info":if(onecard.cardid!=null){loadCard(page,onecard.cardid);}else{window.location='http://onecardme.com/home/';return;}
break;case"profile":case"education":case"employment":changePage("bio.html");break;case"directory":case"favorites":$.confirm({'title':'Redirect to QRPro','message':'No Card ID was request or Requested Card ID was not found. You will be redirect to QRPro\'s website temporarily until the new Directory has been completed.','buttons':{'Okay':{'class':'blue','action':function(){window.location='http://home.qrpro.co/directory';}}}});break;case"debug":case"help":case"bookmark":case"compatibility":case"share":case"video":case"settings":case"app":case"import":case"landing":case"code":changePage("index.html");break;case"qrpro":window.location='http://onecardme.com/home/';break;default:changePage("index.html");break;}}